import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { SchedulerService } from 'src/app/services/scheduler.service';
import {Globals} from '../../global'
import { NgxSpinnerService } from 'ngx-spinner';

declare var $;

@Component({
  selector: 'app-email',
  templateUrl: './email.component.html',
  styleUrls: ['./email.component.scss']
})
export class EmailComponent implements OnInit {

  public planData: any;
  public emailData: any;
  public reviewData: any;

  public showPlan: any = "";
  public showEmail: any = "d-none";
  public showReview: any = "d-none";

  public dataTable: any;
  public parentData: any = [];

  @ViewChild('planTable') planTable;
  @ViewChild('emailTable') emailTable;
  @ViewChild('reviewTable') reviewTable;

  public index: any = 0;
  public email_id: any = 0;

  public d1: any = 0;
  public d2: any = 0;
  public d3: any = 0;

  constructor(private schedulerService: SchedulerService, private router: Router, private globals: Globals, private spinner: NgxSpinnerService) {
  }

  ngOnInit() {
    this.loadPlans();
  }

  loadPlans() {
    /*var dtOptions = {
      language: {
        emptyTable: "Add Parent(s) to show data for the Plan"
      }
    };*/
    this.planData = this.schedulerService.getPlan();
    if(this.planData.length == 0) {
      $("#buttonStage").prop('disabled', true);
      this.schedulerService.resetPlan();  
      var table = $(this.emailTable.nativeElement).DataTable();
      table.clear().draw();
      table = $(this.planTable.nativeElement).DataTable();
      table.clear().draw();
      table = $(this.reviewTable.nativeElement).DataTable();
      table.clear().draw();
    }
    else {
      this.spinner.show();
      $("#buttonStage").prop('disabled', false);
      this.dataTable = $(this.planTable.nativeElement);
      setTimeout(()=>{this.dataTable.dataTable(); this.spinner.hide()}, 10);
    }
  }

  editPlan(i) {
    this.index = i;
    this.parentData = this.schedulerService.getPlan();
    this.d1 = this.parentData[i].d1;
    this.d2 = this.parentData[i].d2;
    this.d3 = this.parentData[i].d3;

    $('#editPop').modal('show');
    this.loadPlans();
  }

  deletePlan(i) {
    this.index = i;
    this.parentData = this.schedulerService.getPlan();
    this.d1 = this.parentData[i].d1;
    this.d2 = this.parentData[i].d2;
    this.d3 = this.parentData[i].d3;
    this.parentData.splice(i,1);
    this.loadPlans();
  }

  editEmail(i) {
    this.index = i;
    //this.parentData = this.schedulerService.stagePlan(this.planData);
    this.d1 = this.emailData[i].d1;
    this.d2 = this.emailData[i].d2;
    this.d3 = this.emailData[i].d3;

    $('#editEmail').modal('show');
  }

  stagePlan() {
    var dtOptions = {
      dom: '<"top"Bf>rt<"bottom"lip><"clear">',
      buttons: [
          {
            extend: 'excel',
            text: 'Download',
            filename: 'Stage_Plan',
            title: 'Below is the list generated by the Tool based on data loaded. For any change, please contact the Administrator',
            exportOptions: {
              columns: ":visible"
            }
          },
          {
            extend: 'colvis',
            text: 'Columns'
          }
      ]
    };
    this.spinner.show();
    this.schedulerService.stagePlan(this.planData).subscribe(result => {
      this.email_id = result[0].email_id;
      this.emailData = result;
      this.dataTable = $(this.emailTable.nativeElement);
      setTimeout(()=>{this.dataTable.dataTable(dtOptions); this.spinner.hide()}, 1000);
    });
    this.showPlan = "d-none";
    this.showEmail = "d-none";
    this.showReview = "";
  }

  showBySupplier(email_id) {
    var dtOptions = {
      dom: '<"top"Bf>rt<"bottom"lip><"clear">',
      buttons: [
          {
            extend: 'excel',
            text: 'Download',
            filename: 'Stage_Plan',
            title: 'Below is the list generated by the Tool based on data loaded. For any change, please contact the Administrator',
            exportOptions: {
              columns: ":visible"
            }
          },
          {
            extend: 'colvis',
            text: 'Columns'
          }
      ]
    };
    this.spinner.show();
    this.schedulerService.getPlanBySuppliers(email_id).subscribe(result => {
      this.reviewData = result;
      this.dataTable = $(this.reviewTable.nativeElement);
      setTimeout(()=>{this.dataTable.dataTable(dtOptions); this.spinner.hide()}, 10);
    });
    this.showPlan = "d-none";
    this.showEmail = "";
    this.showReview = "d-none";
  }

  sendPlan(id) {
    this.schedulerService.sendPlan(id).subscribe(result => {
    });
    this.showPlan = "";
    this.showEmail = "d-none";
    this.showReview = "d-none";
    this.email_id = 0;
    this.planData = [];
    this.emailData = [];
    this.reviewData = [];
    this.schedulerService.resetPlan();
    this.loadPlans();
  }

  onKeyD1(event) {
    this.d1 = event.target.value;
  }
  onKeyD2(event) {
    this.d2 = event.target.value;
  }
  onKeyD3(event) {
    this.d3 = event.target.value;
  }

  save() {
    this.parentData = this.schedulerService.getPlan();
    this.parentData[this.index].d1 = this.d1;
    this.parentData[this.index].d2 = this.d2;
    this.parentData[this.index].d3 = this.d3;
    this.loadPlans();
  }

  saveEmail() {
    this.schedulerService.updatePlan(this.emailData[this.index].id, this.d1, this.d2, this.d3).subscribe(result => {
      this.emailData = result;
      this.dataTable = $(this.emailTable.nativeElement);
      setTimeout(()=>{this.dataTable.dataTable()}, 10);
    });
  }

  deleteEmail(id) {
    this.schedulerService.deletePlan(id).subscribe(result => {
      this.emailData = result;
      if(this.emailData.length == 0) {
        var table = $(this.emailTable.nativeElement).DataTable();
        table.clear().draw();
        $("#buttonReview").prop('disabled', true);
      }
      else {
        this.dataTable = $(this.emailTable.nativeElement);
        setTimeout(()=>{this.dataTable.dataTable()}, 10);
        $("#buttonReview").prop('disabled', false);
      }
    });
  }
}
